compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

logFilters:
  - code: YN0004
    level: discard

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
  # Issue: yargs-parser Vulnerable to Prototype Pollution
  # URL: https://github.com/advisories/GHSA-p9pc-299p-vxgp
  # The affected version (<5.0.0) is only included via
  # @ensdomains/ens via 'solc' which is not used in the imports
  # we use from this package.
  - 1088783
  - 1089718 # GHSA-257v-vj4p-3w2h https://github.com/advisories/GHSA-257v-vj4p-3w2h
  - '@material-ui/core (deprecation)'
  - 'eth-sig-util (deprecation)'

npmRegistries:
  'https://npm.pkg.github.com':
    npmAlwaysAuth: true
    npmAuthToken: '${GITHUB_PACKAGE_READ_TOKEN-}'

npmScopes:
  metamask:
    npmRegistryServer: '${METAMASK_NPM_REGISTRY:-https://registry.yarnpkg.com}'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
    spec: 'https://raw.githubusercontent.com/LavaMoat/LavaMoat/main/packages/yarn-plugin-allow-scripts/bundles/@yarnpkg/plugin-allow-scripts.js'
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'

yarnPath: .yarn/releases/yarn-4.0.0-rc.48.cjs
